### ISSUE TITLE
Error on opening secplus_rx.grc

### ISSUE THREAD

**Issue by camswx** [argilo/secplus#1] opened 2016-12-26 20:36 UTC
Error: too many values to unpack

I'm new to GRC and no python wizard - could this simply be an issue with my environment?

**Comment by argilo** [comment] 2016-12-27 20:51
First of all, what version of GNU Radio are you using? You must have at least 3.7.9, since the GRC file uses an embedded Python block.

By the way, secplus_rx.py is the compiled version of secplus_rx.grc so you should be able to run that directly (and I imagine it will work even if you have an older version of GNU Radio).

If you still aren't able to get it going, please paste in the entire output so I can have a closer look at what went wrong.

**Comment by camswx** [comment] 2017-01-09 20:22
Trying secplus_rx.py (on OS X):

Traceback (most recent call last):
  File "secplus_rx.py", line 229, in <module>
    main()
  File "secplus_rx.py", line 217, in main
    tb = top_block_cls()
  File "secplus_rx.py", line 43, in __init__
    qtgui.util.check_set_qss()
AttributeError: 'module' object has no attribute 'util'

**Comment by argilo** [comment] 2017-01-10 00:35
Do you have GNU Radio installed and working? I'm afraid that without that, you won't be able to use secplus.

**Comment by camswx** [comment] 2017-01-10 13:01
I do, and it appears to be working. I'll switch to a Linux system with a clean install and try again. Ultimately what I'm trying to do is build a docker container for this to increase accessibility/portability.

**Comment by argilo** [comment] 2020-08-15 19:36
I'm closing this, since the issue is very old. If you're still having trouble, please let me know.

**Closed by argilo** 2020-08-15 19:36 UTC
