### ISSUE TITLE
TX gets a "no supported device" where RX does not

### ISSUE THREAD

**Issue by ksaye** [argilo/secplus#14] opened 2022-12-30 21:09 UTC
when I run the RX command, it finds the RTL2838 device

when I run the TX command, I get a 'No supported devices found' error.

> ksaye@up1:~$ cd /opt/gdoor/secplus/
> ksaye@up1:/opt/gdoor/secplus$ ./secplus_rx.py
> Warning: failed to XInitThreads()
> gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.10.5.0
> built-in source types: file rtl rtl_tcp rfspace redpitaya
> Using device #0 Realtek RTL2838UHIDIR SN: 00000001
> Found Rafael Micro R820T tuner
> [R82XX] PLL not locked!
> Exact sample rate is: 2000000.052982 Hz
> [R82XX] PLL not locked!
> ksaye@up1:/opt/gdoor/secplus$ ./secplus_tx.py --freq 315150000 --rolling 2731817118 --fixed 876029924
> gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.10.5.0
> built-in sink types: redpitaya file
> Traceback (most recent call last):
>   File "./secplus_tx.py", line 152, in <module>
>     main()
>   File "./secplus_tx.py", line 135, in main
>     tb = top_block_cls(fixed=options.fixed, freq=options.freq, rolling=options.rolling)
>   File "./secplus_tx.py", line 51, in __init__
>     self.osmosdr_sink_0 = osmosdr.sink(
> RuntimeError: No supported devices found (check the connection and/or udev rules).

**Comment by argilo** [comment] 2022-12-30 21:12
Do you have a transmit-capable radio? RTL2838 devices are receive-only.

**Comment by ksaye** [comment] 2022-12-30 21:14
That has to be it!  What affordable transmit-capable radios have you tested with?

P.S., great project!

**Comment by argilo** [comment] 2022-12-30 21:23
I've tested with HackRF, but other devices (USRP, PlutoSDR, BladeRF, etc) should also work.

I'll close this issue off, since things appear to be working as intended.

**Closed by argilo** 2022-12-30 21:23 UTC

**Comment by ksaye** [comment] 2022-12-30 21:30
Thanks and yes I agree close this.
